### ISSUE TITLE
CORS changes? 

### ISSUE THREAD

**Issue by rwieruch** [algolia/hn-search#106]
I cannot see a recent change that may have caused this, but didn't anything change around CORS for the hn.algolia.com/api/v1 API? I get the following message when I run a query on my localhost application, but also in production (client-side):

`Failed to load https://hn.algolia.com/api/v1/search?query=foo&page=0&hitsPerPage=100: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

Sadly I use the API to teach students about React and many of them are affected. If there was a change, what can I do to fix it on my end? Otherwise, anything I can do to have a workaround for it? I can only imagine to build my own Hacker News proxy server, but I would like to keep my students using an official API to learn programming/React.

* https://intense-refuge-78753.herokuapp.com/
* https://frozen-waters-31575.herokuapp.com/

**Comment by redox** [comment]
Ah yes you’re right! The recent migration we’ve done on the underlying hardware lost that. Gonna fix it ASAP, cc @antoinegauvain

**Comment by rwieruch** [comment]
Thank you so much! Meaning that it should work in browser applications again? ❤️

**Comment by antoinegauvain** [comment]
indeed, the CORS was not applied correctly on our end; should be fixed now, let me know if you still experience issues

**Comment by rwieruch** [comment]
Works again! Thanks for your quick response and fix. I thought I had to revamp all my articles depending on your API :) Thanks for providing such a great experience.

**Comment by redox** [comment]
Awesome! Thank you @antoinegauvain

**Comment by PriyankaKodali** [comment]
ThankYou

**Comment by akshayjamwal07** [comment]
Getting the same issue again.
Can you please have a look if something is changed?

**Comment by JonasBa** [comment]
@akshayjamwal07 We haven't deployed anything recently that could have affected this. Looking at the 2 apps shared by @rwieruch that still use our API, everything remains functional.

**Comment by daviduzondu** [comment]
Access to fetch at 'https://hn.algolia.com/api/v1/items/34866148' (redirected from 'http://hn.algolia.com/api/v1/items/34866148') from origin 'http://localhost:5173' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

What is going on?
