### ISSUE TITLE
Children of children no longer returned in the /items/:id response

### ISSUE THREAD

**Issue by jdormit** [algolia/hn-search#110]
Previously, a call to `/v1/items/:id` would return the item and its children, as well as the children of the children, the great-grandchildren, etc. Now the response includes the children of the root item, but none of those children have a `children` field. For an example, check out https://hn.algolia.com/api/v1/items/16099969.

This is bad for clients since it necessitates multiple requests to fetch the complete comment tree for a story, which gets very slow.

Was this an intentional change?

**Comment by redox** [comment]
This was another regression of the recent gem (especially active_model_serializer) upgrades. Everything should be good now!
