### ISSUE TITLE
Exact match searches for ".NET" stories

### ISSUE THREAD

**Issue by mattwarren** [algolia/hn-search#114]
It's hard to search for storied about ".NET" (the Microsoft runtime/platform), because you also get a lot of titles with "NET" in them

If you compare these 2 searches, the results are the same, so it seems like the '.' is always stripped out?

- [Net](https://hn.algolia.com/?query=Net&sort=byPopularity&prefix=false&page=0&dateRange=all&type=story)
- [".Net"](https://hn.algolia.com/?query=%22%20.Net%22&sort=byPopularity&prefix=false&page=0&dateRange=all&type=story)

Is there a way to search for just .NET stories?

**Comment by JonasBa** [comment]
@mattwarren this is now fixed and should work. FYI Algolia has a [separatorsToIndex](https://www.algolia.com/doc/api-reference/api-parameters/separatorsToIndex/) option which was used to fix this edge case :)

**Comment by mattwarren** [comment]
Oh wow, I'd completely forgotten about this issue, thanks for the fix!
