### ISSUE TITLE
Bad comment links URLs - template variables not interpolated

### ISSUE THREAD

**Issue by myfonj** [algolia/hn-search#118]
String interpolation in
https://github.com/algolia/hn-search/blob/bbf09e3273cbdfce77496d6b66ace7b22c042bb7/app/assets/templates/home.html.haml#L51-L58
```haml
%a{'ng-href' => 'https://news.ycombinator.com/user?id={{ comment.author }}', …}
```
produces bad URLs:
```html
<a ng-href="https://news.ycombinator.com/user?id= comment.author }}" (…)>
```
![image](https://user-images.githubusercontent.com/1761395/40114263-7e99e9f4-590c-11e8-9ae8-15502826f59e.png)

---
Similar link in the same template is correctly produced by plain concatenation:
https://github.com/algolia/hn-search/blob/bbf09e3273cbdfce77496d6b66ace7b22c042bb7/app/assets/templates/home.html.haml#L18

**Comment by myfonj** [comment]
Nope, I don't have sufficient environment at hand nor Ruby / Haml / Angular knowledge to verify it will work so I don't want to make a blind PR.

**Comment by redox** [comment]
Arg, on it!

**Comment by redox** [comment]
@myfonj should be deployed!

**Comment by myfonj** [comment]
Nice to see such a quick response, but hn.algolia.com seems to be still the same:

![image](https://user-images.githubusercontent.com/1761395/40186541-a27d18f2-59f5-11e8-9970-d7b957b95a7e.png)

↑ https://hn.algolia.com/?query=&sort=byPopularity&prefix&page=0&dateRange=all&type=story with comments opened taken 'now' (2018-05-17T17:13)
