### ISSUE TITLE
API request: All comments by a certain user?

### ISSUE THREAD

**Issue by ivmarkp** [algolia/hn-search#124]
Does such an API already exist that I've missed?

I'm thinking: `http://hn.algolia.com/api/v1/search?tags=comment,author_X`

**Comment by JonasBa** [comment]
@ivmarkp Yes it does. Try searching for `author:pg` and set to search by comments. Additionally if you want to search inside the comments, you can do `author:pg $QUERY` and it will do that :)

![image](https://user-images.githubusercontent.com/9317857/64975956-804ec380-d8b0-11e9-9491-6b67b881c7bc.png)

If you want to do this via the API, you will need to use tagFilters. So for the equivalent search above, you will need to use an `AND` operator for tagFilters so the query payload would look something like this

```js
{
  query: "some query",
  tagFilters: ["comment", ["author_pg"]]
}
```

See our [tagFilters API documentation](https://www.algolia.com/doc/api-reference/api-parameters/tagFilters/) for more info on this.
