### ISSUE TITLE
Can't retrieve more than 1000 hits

### ISSUE THREAD

**Issue by ivmarkp** [algolia/hn-search#125]
Is there a limit set for the maximum number of hits that can be returned? I'm using the following API url to get 99999 hits but only 1000 hits being received.

```
http://hn.algolia.com/api/v1/search_by_date?tags=story&numericFilters=created_at_i>1210098600,created_at_i<1525631400&hitsPerPage=99999"))
```

**Comment by JonasBa** [comment]
@ivmarkp we support a `page` parameter, but yes, the max hitsPerPage is 1000. So feel free to use the page param to go further.
