### ISSUE TITLE
An odd entry for front_page

### ISSUE THREAD

**Issue by anykao** [algolia/hn-search#127]
I'm trying to get hn's front stories by using 
> http://hn.algolia.com/api/v1/search?tags=front_page

but it always returns a `2015-06-28` story.

> U.S. Manufacturing costs are almost as low as China’s

That's weird since other stories look fine. (not exactly the same as hn's front page, but reasonable).

Did i miss something?

**Comment by JonasBa** [comment]
Hey @anykao do you still have issues with this? I just manually checked and the stories are all correctly sent. Closing for now, but please let me know if it keeps happening
