### ISSUE TITLE
Is Search broken?

### ISSUE THREAD

**Issue by prashantkhurana** [algolia/hn-search#138]
Hi,

Apologies if this is not the correct forum for reporting this. 

Has there been a already known regression or intentional change to search results? For example : It doesn't seem like "popularity for all time" option is working as intended.

Results for apple sorted by popularity for all time : https://hn.algolia.com/?query=apple&sort=byPopularity&prefix&page=0&dateRange=all&type=story .Clearly these are not the most popular apple articles on hn. 

![image](https://user-images.githubusercontent.com/6133816/53714628-2bb88f00-3e1d-11e9-885c-e7a0202c5564.png)

**Comment by Haroenv** [comment]
<img width="1118" alt="screenshot 2019-03-04 at 10 13 38" src="https://user-images.githubusercontent.com/6270048/53722594-39463700-3e66-11e9-9444-f16f082ebc0e.png">

I'm seeing more relevant results for that all time query. cc @JonasBa

**Comment by prashantkhurana** [comment]
Its working for me too now. When I filed the bug it wasn't working (in incognito mode and otherwise). Could be a location specific, cache issue maybe? 

i'll close the bug. Thanks for the prompt response :)
