### ISSUE TITLE
Is search down?

### ISSUE THREAD

**Issue by InstanceOfMichael** [algolia/hn-search#141]
https://status.algolia.com/hn this page shows nginx 404 white page. 

The search itself shows the loading spinner indefinitely. It's not worked for new for me at least the last three days.

**Comment by Haroenv** [comment]
cc @JonasBa. Do you see error messages in the console loading the regular search page? It seem to be working for me, but you're right that the status page you linked is down.

**Comment by InstanceOfMichael** [comment]
I tried more things. It shows the loading indicator on all 4 versions of Firefox for Android. It works fine on Dolphin browser for Android. It works on chrome and firefox desktop.

**Comment by sgabler** [comment]
I have the same issue on Firefox mobile for Android. The spinning wheel keeps spinning indefinitely. Other Android browsers work fine for me. Had that issue for a couple of weeks, but only just discovered this repo here.

**Comment by JonasBa** [comment]
Could you please check if you see any errors in the console? We have been trying to reproduce the issue without success using browserstack. If you see any errors or could provide us more information that would make it easier to debug we’d greatly appreciate it 🙌🏼

**Comment by sgr-amboss** [comment]
Here's what it looks like for me (in a private window):
![algolia](https://user-images.githubusercontent.com/25818354/54476739-2554ea80-4801-11e9-8d4b-435305cffe8c.gif)

The console output:
![image](https://user-images.githubusercontent.com/25818354/54476765-63eaa500-4801-11e9-9008-efd13db6b827.png)

That Google Analytics warning is caused by ublock origin. But I also have the same spinning wheel if i disable ublock origin.

Nothing stands out for me in the console, but the network panel shows a couple of `500`s:
![image](https://user-images.githubusercontent.com/25818354/54476800-a613e680-4801-11e9-86ad-e2f03ffe7e20.png)

I also disabled "Do not Track" and "Tracking Protection" in the Settings, but the result was the same.

-----
Here are the headers from one of those 500s.

**Request**
```
POST /dev/v1/measure HTTP/1.1
Host: telemetry.algolia.com
User-Agent: Mozilla/5.0 (Android 8.0.0; Mobile; rv:65.0) Gecko/65.0 Firefox/65.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: en-US,de-DE;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
Referer: https://hn.algolia.com/?query=Microsoft&sort=byPopularity&prefix=false&page=0&dateRange=all&type=story
Content-Type: text/plain;charset=UTF-8
Content-Length: 95
Connection: keep-alive
Cookie: __cfduid=d2dfabea329792d41b64d434037c6a1751551360835; _ga=GA1.2.1209937608.1552747374; _gid=GA1.2.892106583.1552747374
```

**Response**
```
HTTP/2.0 500 Internal Server Error
date: Sat, 16 Mar 2019 14:44:46 GMT
content-type: text/html
x-amzn-requestid: 0b4925fc-47fa-11e9-8d22-8bb3b3019059
x-amzn-remapped-content-length: 291
x-amz-apigw-id: Wo7K0GTIliAFugw=
x-amzn-trace-id: Root=1-5c8d0bde-7781d817c207127ebcbafd91;Sampled=0
x-cache: Error from cloudfront
via: 1.1 aec69d2871c7aeb74988020f07480fa4.cloudfront.net (CloudFront)
x-amz-cf-id: lnyNbFmQO7exXuLPhWZajQ883D_XAuHfTnrHmWSnZ03NO5pi7r5jUw==
strict-transport-security: max-age=31536000; includeSubDomains; preload
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 4b8781d088652d95-TXL
X-Firefox-Spdy: h2
```

Notice the `x-cache: Error from cloudfront` in the response. Maybe this is related?

**Comment by JonasBa** [comment]
Thanks a lot @sgr-amboss, I'm having a look and I have a feeling of what could be wrong. It seems that the timeout is set to NaN, which should not be the case. We have been testing better adjustments of timeouts depending on the network that our users are on and it seems that I've broken the adjustments in the last release. Updating it now, thanks a lot for taking the time and effort to send me the console output ❤️

**Comment by sgr-amboss** [comment]
Just realized that the gif i posted was cut after a few seconds. I probably messed up somewhere. Here's the actual gif:
![algolia2](https://user-images.githubusercontent.com/25818354/54477262-8f23c300-4806-11e9-8220-1e0ca9595dd6.gif)

Thank you for taking a look, but at least for me this issue can definitely wait. No need to sacrifice your weekend 😉

**Comment by JonasBa** [comment]
@sgr-amboss thanks a lot, definitely not an issue! I've just deployed a fix. Thanks again for the detailed report, it helped me quickly debug the issue and fix it, appreciate the help 🙌 Let me know if you still see some odd behaviour :)

**Comment by sgr-amboss** [comment]
Thank you. It now works perfectly! 🥇
