### ISSUE TITLE
HN Search using ReactJS

### ISSUE THREAD

**Issue by ojaswa1942** [algolia/hn-search#145]
This is not a suggestion or an issue.
I recreated the website to some extent, using React as a part of an assignment, and wanted to bring this to everyone's notice, just in case it is required now or sometime in future. 
You can find the same here: [Github Repo](https://github.com/ojaswa1942/hn-search) & [Website](https://hn.ojaswa.me).

**Comment by Haroenv** [comment]
Very cool  work!

**Comment by JonasBa** [comment]
This is very cool @ojaswa1942! I'll be in contact, we have just migrated the website to use rails 5, so a next potential improvement would be to migrate it to React.

**Comment by ojaswa1942** [comment]
That'd be great @JonasBa! Looking forward.

**Comment by JonasBa** [comment]
@ojaswa1942 feel free to have a look at https://github.com/algolia/hn-search/pull/150, we should have something ready by eow. Closing this in favour of the PR :) Thank you for the contribution, it was great inspiration to get the work done!
