### ISSUE TITLE
500 Internal Error every 3-4 times

### ISSUE THREAD

**Issue by Pranoy1c** [algolia/hn-search#146]
It was working fine last night. But for the past few minutes, I have been getting:

`{"status":500,"error":"Internal Server Error"}`

Using a simple URL like:

[https://hn.algolia.com/api/v1/search?query=boeing](https://hn.algolia.com/api/v1/search?query=boeing)

It did start working fine few seconds ago but then broke again and started giving the same internal error again. So I tried it a few times and every 4-5th time, it breaks and then retrying a few times starts working again. Could this be some load balancing issue sending the request to some broken component?

**Comment by JonasBa** [comment]
@Pranoy1c Thanks for reporting this, we have updated some dependencies today and it seems like something is unpredictably breaking. Could you maybe give us an example of the error that you are seeing or more information so that we can isolate it?

**Comment by Pranoy1c** [comment]
@JonasBa Thanks for the quick response! The `{"status":500,"error":"Internal Server Error"}` is really all I am getting and I can reproduce it in both Safari and Chrome. It breaks every 4-5 times and if I keep retrying, it works again every 4-5 times. 

Try pasting this in the browser a few times:

(https://hn.algolia.com/api/v1/search?query=test)[]

and refresh the page a few times and you will notice it break again.

**Comment by Pranoy1c** [comment]
@JonasBa I added more info with browser info.

**Comment by JonasBa** [comment]
@Pranoy1c thanks! I've identified the issue by running this locally, see this commit for the fix https://github.com/algolia/hn-search/commit/53f46542546c8153e95086ee417f34d70ddbe467

I will deploy this tomorrow, as it's midnight my time here, just to be safe. Thanks for reporting, should be fixed soon!

**Comment by Pranoy1c** [comment]
@JonasBa Thank you for the quick responses and fix! I will try tomorrow and report back!

**Comment by JonasBa** [comment]
I've deployed the changes and seems that the error is fixed! Thanks for reporting :)

**Comment by Pranoy1c** [comment]
@JonasBa Yes, it's fixed as of yesterday! Thank you again for the prompt responses! :)
