### ISSUE TITLE
Facing CORS issue

### ISSUE THREAD

**Issue by akshayjamwal07** [algolia/hn-search#148]
I am facing CORS issue when i am trying to connect to an end point from my Angular application.
Can you please look into it? See the tracktrace below- 
Access to XMLHttpRequest at 'https://hn.algolia.com/?query=&sort=byPopularity&prefix=&page=0&dateRange=All&type=story' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by akshayjamwal07** [comment]
getting the same issue for search query api as well (stack trace below)-

Access to XMLHttpRequest at 'http://hn.algolia.com/api/v1/search?query=&page=0&tags=story' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.

**Comment by JonasBa** [comment]
@akshayjamwal07 Have you tried 127.0.0.1 instead of localhost?  Chrome does not allow cors on localhost. https://bugs.chromium.org/p/chromium/issues/detail?id=67743

**Comment by akshayjamwal07** [comment]
Thanks for the suggestion, it got resolved. I am not sure how as I made no changes in my code to fix that. :)
