### ISSUE TITLE
Firefox: TypeError: window.$ is undefined

### ISSUE THREAD

**Issue by qsantos** [algolia/hn-search#156]
I get the following on Firefox 69.0 on Debian stable (10.1). The weird thing is that I was not able to reproduce the issue from a fresh Firefox profile, and neither disabling addons, allowing cookies, trackers and such, “forgotting the website” from the history tab, or using privacy browsing fixed the issue. I might have missed something else to try.

![Capture d’écran_2019-09-12_20-43-54](https://user-images.githubusercontent.com/8493765/64811701-0c55a800-d59e-11e9-96e2-3d67125a5e66.png)

![Screenshot_2019-09-12 HN Search powered by Algolia](https://user-images.githubusercontent.com/8493765/64811884-69e9f480-d59e-11e9-867a-e723a48790b2.png)

**Comment by Scrxtchy** [comment]
Still an issue on (dev) 70.0b6

**Comment by Haroenv** [comment]
I think this might happen because of this line @JonasBa https://github.com/algolia/hn-search/blob/c79d987a0bd43d654e02ae100903c0b246c3afb9/app/javascript/utils/telemetry.ts#L69

**Comment by qsantos** [comment]
I confirm that `window.$` is not defined when I browse hn-search and type it in the developer console.

**Comment by JonasBa** [comment]
Thanks, fixing this asap now!

**Comment by JonasBa** [comment]
I merged a fix and will deploy this first thing tomorrow morning as we've just added some other changes in too. Thanks for reporting!

**Comment by qsantos** [comment]
I confirm that the issue is fixed!
