### ISSUE TITLE
Story_link without word-break causes Story_container overflow

### ISSUE THREAD

**Issue by brettinternet** [algolia/hn-search#160]
## Bug

In mobile views, story links do not have word-break rules which causes some stories to overflow-x outside of their containers. This causes x-axis scrolling and creates a frustrating experience for mobile users.

![story overflow screenshot example](https://user-images.githubusercontent.com/20871604/66062906-87581180-e4ff-11e9-909a-b7d924ae4c09.png)

### 1. Add `word-break: break-all` to `.Story_link` CSS class.

![fix 1 example screenshot](https://user-images.githubusercontent.com/20871604/66063056-daca5f80-e4ff-11e9-983d-5bf3387fdee4.png)

The result does cause some awkward breaks in the root domain of the Story Link. These `break-all` might be more acceptable in the pathname, rather than the root location, which is typically a more important qualifier to evaluating a domain.

### 2. Add `word-break: break-all; display: block;` to `.Story_link` and remove `margin-left: 4px;`.

![fix 2 example screenshot](https://user-images.githubusercontent.com/20871604/66063435-955a6200-e500-11e9-8aa3-7fb76f3efc12.png)

We may also consider removing the parenthesis, since the new line is enough of a delimiter between the title and the URL.

![fix 2 example screenshot without parenthesis](https://user-images.githubusercontent.com/20871604/66063645-0c8ff600-e501-11e9-8950-680a92de8a0a.png)

### Adding `word-break: break-word` to `.Story_link` (`break-word` instead of `break-all`)

![example screenshot using break-word](https://user-images.githubusercontent.com/20871604/66063960-b3749200-e501-11e9-9d2f-a34a1f0af8e7.png)

The result does not fix existing issues with the Story Title where depending on where the words break in the URL, the title may experience unfortunate line breaks and awkward spacing.

---

What does the team consider the best approach to honoring the original simple styling while correcting the overflow?

I'd love to submit a PR.

**Comment by JonasBa** [comment]
Thank you again @brettinternet :)
