### ISSUE TITLE
meta color-scheme tag makes certain elements hard to read

### ISSUE THREAD

**Issue by saagarjha** [algolia/hn-search#168]
The addition of `<meta content='light dark' name='color-scheme'>` (#165) is great, but it makes certain elements a bit hard to read, such as the text in the search box and the elements in the menu:

<img width="1392" alt="Screen Shot 2019-11-08 at 03 17 56" src="https://user-images.githubusercontent.com/13786931/68472874-5f329100-01d6-11ea-87f7-056f6fa14b34.png">

Could the colors for these depend conditionally on `@media(prefers-color-scheme)`?

**Comment by JonasBa** [comment]
@saagarjha! Let us handle this and see with the YC team if we could add the dark theme to this layout too. Could you go to settings and switch to experimental layout and let us know how that looks for you?

Thanks a lot!

**Comment by saagarjha** [comment]
Hi, thanks for the reply! I turned on the experimental layout and I'm still seeing this issue on certain controls, plus the theme doesn't seem to respond to the system color scheme:

<img width="1392" alt="Screen Shot 2019-11-10 at 00 03 46" src="https://user-images.githubusercontent.com/13786931/68540900-924b6080-034d-11ea-8a51-d94e90b092ba.png">

Is there an option to make this work somewhere? I couldn't seem to find it :(
