### ISSUE TITLE
favicon has old logo

### ISSUE THREAD

**Issue by Haroenv** [algolia/hn-search#171]
https://hn.algolia.com/assets/favicon-f54903568e0e9777f2e4db164b19e76ac961d1c283d9dbbff6cc8276188e5179.ico is linked in the  html, but it's using our old logo turned orange

![](https://hn.algolia.com/assets/favicon-f54903568e0e9777f2e4db164b19e76ac961d1c283d9dbbff6cc8276188e5179.ico)

**Comment by JonasBa** [comment]
Hmm, lemme attempt and make this our new logo but with this same orange
