### ISSUE TITLE
Issue #60 rides again: Inadvertant cross-site scripting from HN posts

### ISSUE THREAD

**Issue by thejerf** [algolia/hn-search#173]
Same post is doing it.

Opening a new issue because I can't reopen the old one, and I'm not sure that would get attention anyhow.

**Comment by thejerf** [comment]
https://github.com/algolia/hn-search/issues/60 for convenience.

**Comment by Haroenv** [comment]
https://hn.algolia.com/?query=Cross-site%20scripting%20includes&sort=byPopularity&prefix&page=0&dateRange=all&type=comment I can indeed see the XSS happening on this URL. Good catch @thejerf

**Comment by Haroenv** [comment]
I think it's going to lead from here: https://github.com/algolia/hn-search/blob/master/app/javascript/components/Story/Story.tsx#L77

**Comment by JonasBa** [comment]
Thank you very much for this, do you mind reviewing this => https://github.com/algolia/hn-search/pull/174 :)?

**Comment by thejerf** [comment]
I'm not sure who you're asking to review that; if it's me, I'm not really competent to do it without going much wider into the code base than I'm comfortable with. Certainly removing "dangerouslySetInnerHTML" sounds like a good idea, but I don't know what other encoding issues are going to appear as a result. I recall from last time that the data coming from HN itself is rather quirky.
