### ISSUE TITLE
Search doesn't appear to be working

### ISSUE THREAD

**Issue by dsnyder** [algolia/hn-search#178]
Hitting https://hn.algolia.com gives me the following
`GET https://hn.algolia.com/packs/js/application-462cf6a8191e54a9e659.js net::ERR_ABORTED 404`

and going to https://status.algolia.com/hn gives me an nginx error similar to #141

**Comment by JonasBa** [comment]
I see an intermittent error coming from our Sentry, but we haven’t done any deployments in the past weeks so I’m not sure what to correlate this with. When I visit HN I can still access the search and the website works well. Would you mind telling me which location you are trying to access this from?

I dont have laptop access right not (traveling back home), but I will give this a look first thing tomorrow morning. Thanks for the help!

**Comment by dsnyder** [comment]
I was trying to view this from my work and thought maybe there was some policy preventing me from viewing it as I was able to view it from my iPhone. Hitting it from my desktop using Chrome/Firefox/Opera gives me the empty page I described above.

I tried changing the emulated devices in the debugger and I was able to see the page from my desktop while doing that.

The responsive view doesn't show anything.
![2020-03-10 14_25_03-HN Search powered by Algolia](https://user-images.githubusercontent.com/166663/76346485-79db5a80-62db-11ea-8cf8-56e19511ef91.png)

Galaxy 5S / iPhone configurations show the page.
![2020-03-10 14_25_03-HN Search powered by Algolia](https://user-images.githubusercontent.com/166663/76346560-9d060a00-62db-11ea-8b36-beaf2e84a8f1.png)

**Comment by JonasBa** [comment]
@dsnyder I noticed that during deployment, some orphaned processes running thin server were running and werent properly terminated during deployment. Are you still seeing this issue, it should be resolved now?

**Comment by JonasBa** [comment]
@dsnyder feel free to reopen if you see this again!

**Comment by filleduchaos** [comment]
I'm having the same issue - site works on my phone, but doesn't work at all on desktop due to apparently missing CSS/JS files.
