### ISSUE TITLE
Filters are invisible on Safari

### ISSUE THREAD

**Issue by EdmundKorley** [algolia/hn-search#193]
It looks the default stylesheet on Safari Version 13.1.2 (15609.3.5.1.3) is providing a default color on buttons (`buttontext`) that is faded white `rgba(255, 255, 255, 0.847)` and so makes the search filter options invisible against the white background. Seems like a specificity issue which I can take a stab at fixing if you like.

<img width="1440" alt="Invisible Filters Problematic Filter Color" src="https://user-images.githubusercontent.com/13422991/91639756-a12efc80-e9cd-11ea-96cb-7d494110250d.png">

**Comment by Haroenv** [comment]
This seems to be specifically in dark mode indeed.

**Comment by esnard** [comment]
@Haroenv I now have the problem on Firefox, in non-dark mode.

Based on the changes in 2ad3341, the following color has been added for the button:

```css
$dark-text-dark-light: rgba(255,255,255,.85);
```

Which makes the text white.

Am I understanding it correctly?
