### ISSUE TITLE
Would it be possible to filter results with > x replies?

### ISSUE THREAD

**Issue by mlaugharn** [algolia/hn-search#200]
Sometimes I'm looking for big discussion threads but it's over a lot of search result pages. It would be nice to just be able to ignore the ones under a certain number of comments. Also thanks for the awesome search tool!!!

**Comment by dredmorbius** [comment]
This seems to be presently supported:

> Use points>NUMBER or points<NUMBER to filter by points,

https://hn.algolia.com/help

**Comment by mlaugharn** [comment]
Thanks
