### ISSUE TITLE
"Cool App" not showing up

### ISSUE THREAD

**Issue by jstrieb** [algolia/hn-search#205]
Hi! Hopefully this is the right place to discuss this.

A little while ago I made a PR (#203) that was merged to add my Firefox extension to the [Cool Apps page](https://hn.algolia.com/cool_apps). It's been about a month and I don't yet see my change reflected there. Have I done everything that I need to in order for the change to be visible (and it's just a matter of re-deploying on your end)? Is there anything else I need to do to have my listing appear on the page? Thanks!

On another note, thanks for making this search functionality available! Even outside of automated queries, I use the Algolia HN search *constantly* and really appreciate it being available!

**Comment by Pranoy1c** [comment]
Same problem here. My iOS app HACK was added to the cool apps list but the actual page still doesn't reflect the change:

https://github.com/algolia/hn-search/issues/204#event-4488522699

https://github.com/algolia/hn-search/commit/951fd4f9f38c084677c8db8524edcee74d1aa06a

https://hn.algolia.com/cool_apps

It's like something needs to be re-deployed or something?

**Comment by Haroenv** [comment]
cc @redox, it indeed still needs to be deployed, I forgot it wasn't automatic

**Comment by Pranoy1c** [comment]
@redox Would you be able to deploy the changes? Thank you.

**Comment by Haroenv** [comment]
Thanks for your patience @Pranoy1c & @jstrieb, it has now been deployed!

**Comment by redox** [comment]
> @redox Would you be able to deploy the changes? Thank you.

Sorry for being late, thank you @Haroenv for the help!
