### ISSUE TITLE
HN Results Not Populating 

### ISSUE THREAD

**Issue by Zweihander-Main** [algolia/hn-search#215]
As of 5AM GMT Sep 3, [this search for stories in the last 24 hours](https://hn.algolia.com/?dateRange=last24h&page=0&prefix=false&query=&sort=byPopularity&type=story) only returns results 22-24 hours ago (and I suspect will return nothing in 2 more hours). It seems like the data isn't being pulled anymore from HN.

I noticed this after [this API request for stories 24 hours to 12 hours ago](https://hn.algolia.com/api/v1/search?tags=story&numericFilters=created_at_i%3E1630548000,created_at_i%3C1630591200,points%3E12&hitsPerPage=10000) (run at 1AM GMT) failed to come up with any results: 
```
{"hits":[],"nbHits":0,"page":0,"nbPages":0,"hitsPerPage":1000,"exhaustiveNbHits":true,"query":"","params":"advancedSyntax=true\u0026analytics=true\u0026analyticsTags=backend\u0026hitsPerPage=10000\u0026numericFilters=created_at_i%3E1630548000%2Ccreated_at_i%3C1630591200%2Cpoints%3E12\u0026tags=story","processingTimeMS":1}
```

**Comment by redox** [comment]
we're on it @Zweihander-Main

**Comment by redox** [comment]
This has been resolved a few hours later, forgot to close.
