### ISSUE TITLE
type=all is broken

### ISSUE THREAD

**Issue by shreevatsa** [algolia/hn-search#238]
It looks like there's a new version of HN search just pushed to https://hn.algolia.com, which instead of just "Stories" and "Comments" now also allows searching among "Ask HN", "Show HN", "Launch HN", "Jobs", "Polls". This is nice, but in the process the update has broken searching everything (both Stories and Comments) with `type=all`. 

For example, a search like this doesn't work any more: https://hn.algolia.com/?dateRange=all&page=0&prefix=false&query=software&sort=byDate&type=all

This has also broken some existing links, e.g (the following two are **working** links, to searches for finding the **broken** links): 

https://hn.algolia.com/?dateRange=all&page=0&prefix=true&query=algolia%20%22type%3Dall%22&sort=byDate&type=story

and

https://hn.algolia.com/?dateRange=all&page=0&prefix=true&query=algolia%20%22type%3Dall%22&sort=byDate&type=comment

**Comment by jeffrey-slentz-algolia** [comment]
Hey Shreevata, thanks for the comment. We removed `type=all` because we rank items by their score, and comments no longer have a score.

Would it be sufficient to take `type=all` and default to `type=story`?
Or would there be some value to searching both at the same time?

**Comment by shreevatsa** [comment]
I would like to search both stories and comments (as was the behaviour earlier). For example, I usually search by date, a link like this:

https://hn.algolia.com/?query=KEYWORD&sort=byDate&prefix&page=0&dateRange=all&type=all

(with KEYWORD replaced by what I'm searching for), to see whether there's any newer post (of any type: comment or story) mentioning the keyword I'm interested in. This used to work, but now I have to do the search two times. (Or more, if I suspect there may be other types…) (Also at least some of the existing links for type=all were intended to search comments too.)

I understand that when ranking by score/popularity it doesn't make sense to search over both comments and stories, but when sorting by date, as the score doesn't matter, it would be useful to continue to retain the ability to search over all kinds of posts.

Thanks for considering this!

**Comment by jeffrey-slentz-algolia** [comment]
@shreevatsa 
Sorry for the delay, you should find that all is back :)

**Comment by shreevatsa** [comment]
Yes it's working now! Thank you so much!
