### ISSUE TITLE
ID 29067493 throwing 500 Internal Server Error

### ISSUE THREAD

**Issue by SimonBerens** [algolia/hn-search#242]
Specifically, querying https://hn.algolia.com/api/v1/items/29067493 gives a 500 error. Other IDs seem to work fine.

**Comment by jeffrey-slentz-algolia** [comment]
Hey Simon, thanks for the issue, taking a look.

**Comment by jeffrey-slentz-algolia** [comment]
Should be fixed now! :)

**Comment by SimonBerens** [comment]
@jeffrey-slentz-algolia just realized I'm also getting this on ID `24342496`

**Comment by jeffrey-slentz-algolia** [comment]
Wow, looks like a data issue from HN. I've raised it with them and working on a solution :) 

For an example of the type of item affected:
https://hacker-news.firebaseio.com/v0/item/37759249.json?print=pretty
vs
https://news.ycombinator.com/item?id=37759249

**Comment by jeffrey-slentz-algolia** [comment]
We've pushed a fix for the 500 error, but the data may be inconsistent for a few affected items for a few days.

**Comment by SimonBerens** [comment]
Thanks! Can confirm no longer getting errors on my end.
