### ISSUE TITLE
Searching by exact query match?

### ISSUE THREAD

**Issue by theoretick** [algolia/hn-search#28]
Hi, I dont know if there's a parameter for this currently but I want to query results by URL attached to a story. This seemed possible with the old API but cannot seem to query by URL only.

I have tried query matches with a URL but the matching seems to be quite fuzzy and I want exact matches.  Querying `http://hn.algolia.io/api/v1/search_by_date?tags=story&query=http://skimfeed.com/` seems to offer results with a matchedWord that doesn't appear in the text at all. I'm assuming this is a fuzzy-match feature and not a bug, but is there a way to perform a more exact query?

**Comment by Kikobeats** [comment]
@redox I was looking for exactly this, could be nice open a new issue to leverage the functionality as part of the UI

**Comment by redox** [comment]
@Kikobeats the underlying angular 1 code starts to get a little bit outdated but I would love some help to expose such a feature in the UI; any chance you've time to give it a try?

**Comment by satvikpendem** [comment]
How can I search via URL on the website itself rather than API?
