### ISSUE TITLE
Search behavior is inconsistent depending on how search is executed

### ISSUE THREAD

**Issue by dbstraight** [algolia/hn-search#41]
I discovered this when realizing I missed a previous front-page story about "Input Fonts" because I searched for "Input Font". (See: https://news.ycombinator.com/item?id=8173181)

If a search is executed from the text box on HN or by typing the search and pressing enter, exact matching is used. If the search is executed by typing in the search and NOT pressing enter (letting the live results come up), then prefix matching is used.

Example:

If I type "test search" in the box, I get this URL: https://hn.algolia.com/#!/story/forever/prefix/0/test%20search

If I then press enter, I get this URL: https://hn.algolia.com/#!/story/forever/0/test%20search

The latter will not find "tests" or "searched" or other close matches.

**Comment by JonasBa** [comment]
Agree this might be confusing, but we had no one else reporting this. Will close for now :)
