### ISSUE TITLE
Add ability for whole string search

### ISSUE THREAD

**Issue by mrbaker4** [algolia/hn-search#53]
On the old search when I would look for 'ios', it would return items that contained full match.

Currently when I search for 'ios', it returns all results that contain 'io'.

It would be nice if there was a way to specify you want to match the string exactly or partial match is ok.

**Comment by redox** [comment]
Hey @mrbaker4,

You're right, this is a regression due to the "ignorePlurals" flag that I've enabled by default on the new version. So "ios" and "io" were considered the same.

I've just deployed the rollback to production!

**Comment by mrbaker4** [comment]
Awesome! Thanks for fixing so quickly!
