### ISSUE TITLE
Issue searching for comments with points filter

### ISSUE THREAD

**Issue by edavis** [algolia/hn-search#55]
Hi,

It appears the combination of `tags=comment` and `numericFilters=points>X` is no longer returning new results.

The latest results are from early October 2014: https://hn.algolia.com/api/v1/search_by_date?tags=comment&numericFilters=points%3E1

It seems to just be this combination. Searching for comments and filtering on `created_at_i` works fine. Searching for stories and filtering on `points`, `num_comments`, or `created_at_i` works fine.

It looks like a switch was made to the official HN API around early-to-mid October 2014 (#29). My best guess is this issue is related to that switch.

Thanks!

**Comment by redox** [comment]
Yes you're right. The new Firebase-based API doesn't include any score attribute for comments https://github.com/HackerNews/API#items

For instance https://hacker-news.firebaseio.com/v0/item/9023243.json

@kogir any input on that?

**Comment by kogir** [comment]
We never really meant to leak score information, even in the pre-firebase private interface. I don't believe there are plans to bring it back. You'll need to email hn@ycombinator.com and try to convince Daniel :smile:

**Comment by edavis** [comment]
Ah, gotcha. No worries. Just wanted to make sure I wasn't missing something.

**Comment by PatMyron** [comment]
@kogir I understand points aren't shown for other users' comments on HN, but an interface that sorts one's own comments by score would be nice
