### ISSUE TITLE
Breaking change in Access-Control-Allow-Headers?

### ISSUE THREAD

**Issue by Some1Else** [algolia/hn-search#59]
I wrote [a prototype](http://hnthread.ljudje.si) in November, which doesn't seem to work anymore.
```
XMLHttpRequest cannot load http://hn.algolia.io/1/404?tags=story&restrictSearchableAttributes=url&query=%22https://github.com/blog/1986-announcing-git-large-file-storage-lfs%22. Request header field Accept-Encoding is not allowed by Access-Control-Allow-Headers.
```
I'm making this request from the client with JavaScript. I suppose requesting this from the server would let me omit the Accept-Encoding header field. Is that the intended use case?

**Comment by redox** [comment]
Just use `hn.algolia.com` instead of this old `.io` hostname; it should solve the issue!
