### ISSUE TITLE
XSS on https://news.ycombinator.com/item?id=1154379

### ISSUE THREAD

**Issue by thejerf** [algolia/hn-search#60]
A search that views this post ends up actually navigating to "htt://hostile.com".

I see commit 066f1525cb704e5064dd51384678353f72547c19 seems to address XSS issues. I do not know if this commit is deployed to the search application or not, but the approach is fundamentally flawed. You can not filter out badness; you must correctly encode the text such that HTML entities are correctly used. HN posts do not permit HTML to be used within them, so somewhere you need to call an HTML encoding function on the text, which will encode everything that looks like a tag.

The linked post is a decent test case... it really ought to come up in the search engine exactly as it displays on HN, no additional encoding, no removed encoding, nothing filtered out.

I don't know Ruby, but I'm very familiar with this problem in general; if you need some more help, let me know. I often help my coworkers with this.

**Comment by redox** [comment]
Yeah that was kind of a hack because the way HN is storing their data is super weird. They seems to strip some tags, but don't remove all of them. I'll make it more robust, trying to keep as much HTML structure as possible.

Thank you for the bug report and providing the reproduction case @thejerf  :)

**Comment by redox** [comment]
@thejerf actually I'm not able to reproduce it, could you share with me the URL you've used? I used this one: https://hn.algolia.com/?query=Cross-site%20scripting%20includes&sort=byPopularity&prefix&page=0&dateRange=all&type=comment

**Comment by thejerf** [comment]
> They seems to strip some tags, but don't remove all of them

Yeah... I've never really pounded on HN's comment algorithm but it is _definitely_ a hacked up thing itself, which doesn't help. Best of luck dealing with the mess. :)

**Comment by redox** [comment]
@thejerf let me know what you think about that one :+1:

**Comment by redox** [comment]
(Deployed to http://hn.algolia.com)

**Comment by thejerf** [comment]
Yeah, now we're getting &quot; everywhere... I don't suppost you could gist up exactly what the linked post looks like when it comes to you?

**Comment by thejerf** [comment]
I had to dash that comment off and eat dinner; I come back hours later and note that GitHub chewed on my comment, I think. I said we're getting ampersand-q-u-o-t-semi-colon everywhere, which of course Markdown helpfully converts to double quote: " which this time I typed literally. Let's try this again: We're getting &amp;quot; everywhere.

Upshot being, don't feel bad. To a first approximation, nobody gets this right. There's just the set of people who underencode and create XSS, the set that overencode and create excessive ampersands, and the set of people who managed to do both.

&lt;script&gt;alert("hooray world!")&lt;/script&gt;

**Comment by redox** [comment]
Good catch @thejerf.

You can compare https://hn.algolia.com/?query=Cross-site%20scripting%20includes&sort=byPopularity&prefix&page=0&dateRange=all&type=comment and the associated raw data https://hn.algolia.com/api/v1/search?query=Cross-site%20scripting%20includes&tagFilters=comment

**Comment by thejerf** [comment]
Well, at least for that message, it looks like you should be able to take exactly literally what HN sends back and plop it bytewise on to the page; it's at the proper decoding level for that. That would make me vaguely nervous on general principles and I could make myself feel better by using an HTML normalization library, but that would inevitably introduce its own complications. It would be easy to accidentally decode it, which could be what you were seeing; if something accidentally HTML-decoded the string before shipping it out it would become XSS.

You happen to have a message that had an unencoded script tag in it somewhere?
