### ISSUE TITLE
[REQ] Option to exclude username from search

### ISSUE THREAD

**Issue by pbowyer** [algolia/hn-search#65]
For certain searches (e.g. when [looking for comments](https://hn.algolia.com/?query=Julia&sort=byDate&prefix&page=0&dateRange=all&type=comment) about the Julia programming language) the search string matches a number of usernames.

It would be great to have options to restrict the search to matching the comment body, as unless I'm searching for a particular person (for which there's already a search modifier) usernames aren't of relevance.

**Comment by redox** [comment]
Yes that makes a lot of sense. Are you talking about the UI (https://hn.algolia.com) or the API?

**Comment by pbowyer** [comment]
The UI, sorry for not being clear!

**Comment by shreevatsa** [comment]
@redox Given your knowledge of the codebase, could you say what it would take to change this? Could you point to the relevant place/file, in case someone wants to send a PR? :-) 

I imagine that one could change either indexing (don't include the username in the body text at all), or retrieval (don't return results for the username), or the UI (hide username-only results on the page). Not sure what would be best (according to you), or where any of these ought to be changed.

(Also, would it make sense to just change the behaviour, or does this need to be an option?)

**Comment by redox** [comment]
> @redox Given your knowledge of the codebase, could you say what it would take to change this? Could you point to the relevant place/file, in case someone wants to send a PR? :-)
> 
> I imagine that one could change either indexing (don't include the username in the body text at all), or retrieval (don't return results for the username), or the UI (hide username-only results on the page). Not sure what would be best (according to you), or where any of these ought to be changed.
> 
> (Also, would it make sense to just change the behaviour, or does this need to be an option?)

Yes, we could rely on the [restrictSearchableAttributes](https://www.algolia.com/doc/api-reference/api-parameters/restrictSearchableAttributes/) query parameters and make it a setting.

Any chance one of you wants to send a PR?

**Comment by shreevatsa** [comment]
@redox Sent https://github.com/algolia/hn-search/pull/115

**Comment by redox** [comment]
Just deployed it @shreevatsa ; let me know what you think!

**Comment by shreevatsa** [comment]
Works great, thank you!
