### ISSUE TITLE
Userfeed returns "Unknown."

### ISSUE THREAD

**Issue by yubrew** [algolia/hn-search#66]
Following these docs, I am expecting a feed of pg's undeleted comments: `http://hn.algolia.com/userfeed/?username=pg`

However, I get a response of "Unknown." from the server.

It's the same error trying to visit just userfeed: `http://hn.algolia.com/userfeed`

https://github.com/algolia/hn-search/blob/master/app/controllers/home_controller.rb#L38-#L43

Is this functionality no longer supported?

**Comment by redox** [comment]
Oh the correct URL is `http://hn.algolia.com/userfeed/pg` actually :)
