### ISSUE TITLE
Change default time range from 'Last 24h' to 'All Time'

### ISSUE THREAD

**Issue by gwern** [algolia/hn-search#68]
So I periodically submit batches of URLs from a variety of time periods to HN; since not resubmitting links is HN policy, and many of them are old and since it's a good idea to check even for cutting-edge links because someone might've beaten you, I use https://hn.algolia.com to check that each URL has not been submitted to HN before (or, if I really like the content, check that it has not been submitted in at least a year and didn't get much attention then). As I understand it, a lot of other people use it for this purpose too, and this is one of the main purposes, the other being easy search through HN history for topics and keywords.

To do so, every time I go to it, I must change the default time range from 'Last 24h' to 'All Time'. It's not helpful to search the last 24h if it means I miss a submission a year ago (as it would often occur, since many of my links turn out to already be submitted).

This is annoying. (It's even more annoying when I forgot to change the setting on a visit and I have checked a batch of links only to realize I had checked the last 24h.)

So I'd like to propose that the default be changed. Changing the default this way would help everyone checking for past submissions and would also help everyone searching for old comments on particular topics.

It would get in the way of people who only want to see the last 24h of links, I suppose, but I'm not sure why those people would use the search engine for that rather than just go to http://news.ycombinator.com/ directly. Other than that, I'm not sure what advantage 'Last 24h' has over 'All Time' as a default. 

(If you're really unsure about this change, perhaps you could check the web logs/analytics to see how often `dateRange=all` is chosen over `dateRange=last24h` by human visitors and we could get some hard data on what would be an optimal UI choice?)

**Comment by redox** [comment]
That's also something I suffer a lot with actually. I think moving to default value = "All Time" is a good thing :+1:, will do :) Thanks for contributing @gwern

**Comment by gwern** [comment]
Thanks!

**Comment by Shipow** [comment]
Actually I was sure we put that as an option in settings

**Comment by gwern** [comment]
Has this default change been made? When I go to it in a variety of browsers, it still defaults to 24h.

**Comment by redox** [comment]
> Has this default change been made? When I go to it in a variety of browsers, it still defaults to 24h.

Did you open a private session window to test? It's still the case on my side. Then, as @Shipow mentioned: you can change your defaults from the [settings](https://hn.algolia.com/settings).
