### ISSUE TITLE
Sort by popularity doesn't seem to work

### ISSUE THREAD

**Issue by pacemkr** [algolia/hn-search#69]
For example: https://hn.algolia.com/?query=little%20snitch&sort=byPopularity&prefix&page=0&dateRange=all&type=story

First result has 7 points
Ninth has 14 points

**Comment by redox** [comment]
I don't reproduce the behavior @pacemkr; can you add a screenshot?

**Comment by pacemkr** [comment]
Sure. Using Chrome, but same story in Firefox.

Screenshot taken from simply clicking the link.

![screen shot 2015-12-09 at 2 39 25 pm](https://cloud.githubusercontent.com/assets/339051/11696581/fea92188-9e82-11e5-95d9-7e3c8e9357a9.png)

**Comment by redox** [comment]
Oh OK now I understand why I didn't have the same behavior. I forgot I configured my settings (top-right icon) to NOT search in the story text.

The underlying Algolia index is configured in a way to first rank results by textual relevance, **then** by custom/business relevance. Here the `points` is the custom criteria. What it means is that we'll only consider the `points` attribute if the textual relevance is the same.

In your case, what you see is:
 - all results matching in the `title`, sorted by points
 - then all results matching in the `text`, sorted by points

For that specific query, it might be misleading. Does that make sense?

**Comment by pacemkr** [comment]
That makes sense. Thank you.
