### ISSUE TITLE
Google search ranking

### ISSUE THREAD

**Issue by porjo** [algolia/hn-search#70]
When I search for 'hacker news search' in Google, the top result is https://hn.algolia.com/api. The search page (https://hn.algolia.com/) doesn't appear in the search results (at least not on the first page).

When I visitor lands on the API page, it isn't clear how they would use the search facility from their browser.

It would be good to try and get Google ranking the search page higher. Or at least modify the API page to make it clearer to visitors how they can search from the website (e.g. "Click here to go to the search page")

**Comment by redox** [comment]
Good point @porjo; and that's probably because the home page is fully rendered with JavaScript.

I'll go for the quick-win of adding a link; we'll need to think about what we could do better later.

**Comment by porjo** [comment]
Searching for 'hacker news search' now shows the index page as number 1 result.

**Comment by redox** [comment]
:+1: thanks for following up @porjo
