### ISSUE TITLE
Switching from byPopularity to byDate gives null set

### ISSUE THREAD

**Issue by buck** [algolia/hn-search#72]
I was looking for RxAndroid content on Hacker News.

This search returns two pages of results:

https://hn.algolia.com/?query=RxAndroid&sort=byPopularity&prefix&page=0&dateRange=all&type=story

This search returns null:

https://hn.algolia.com/?query=RxAndroid&sort=byDate&prefix&page=0&dateRange=all&type=story

Am I doing something wrong?

**Comment by redox** [comment]
Indeed this behavior is tricky :100: For the sort by date, we disable typo-tolerance and therefore you don't get all the results matching `rx android` or `rundroid` retrieved by the first query.

By default, the Algolia engine sorts by text-relevance criteria (typo-tolerance, matching attributes, ...), then business/custom criteria (here the date). Enabling the typo-tolerance here would allow results with typos and an early date to show up before exact matches with a late date -> producing a very bad search experience.

Does that make sense to you?

**Comment by buck** [comment]
Sure, as long as that is the (now) expected behavior.  Thanks!
