### ISSUE TITLE
scrolling results with arrow keys

### ISSUE THREAD

**Issue by digi-owl** [algolia/hn-search#73]
Using the down arrow works fine, but the up arrow sends me to the top of the results page on a single press.

**Comment by redox** [comment]
@Shipow do you remember why we implemented that behavior? https://github.com/algolia/hn-search/blob/master/app/assets/javascripts/app.js#L184-L185

**Comment by JonasBa** [comment]
We did not persist this behaviour in https://github.com/algolia/hn-search/pull/150
@Shipow last call if you can remember why this was implemented this way?
