### ISSUE TITLE
Page 3 of results for "PCI Compliance" doesn't exist

### ISSUE THREAD

**Issue by scottopell** [algolia/hn-search#74]
With this [search](https://hn.algolia.com/?query=pci%20compliance&sort=byPopularity&prefix=false&page=0&dateRange=pastYear&type=comment), I get invalid results starting on page 3.

I see that there are 135 results. As I go through them, page 1 (page 0 in the GET params) has results, same with page 2, but then when I click on page 3 (page 2 in GET params), the page says 

> No comments matching pci compliance in the past year

It still says page 3 of 12 in the upper right hand corner.

And if I try to go page 4 (or some greater page) by changing the GET params, it just hangs forever.

**Comment by JonasBa** [comment]
@scottopell I can't seem to reproduce this anymore so I'm closing the issue. Let me know if you keep seeing this.
