### ISSUE TITLE
Query ordering

### ISSUE THREAD

**Issue by vvo** [algolia/hn-search#78]
Following the article of hashnode, https://hashnode.com/post/how-we-built-our-new-search-using-algolia-cinemi2300008e153l9i6gxj6 and the part about the failing HN news search on weird conditions.

I read through the code and added some debugs, it seems that that line: https://github.com/algolia/hn-search/blob/e68a874f256c25d6dcea7a9a8e0fa3ea2d387710/app/assets/javascripts/controllers.js#L117

is not checking that the current input query value is equal to the request query value, but just that some internal current query value is equal to the hits query.

Dunno exactly where to fix that, need some more investigation/help @redox

**Comment by redox** [comment]
Thank you @vvo, your comment made me realize where the bug was!
