### ISSUE TITLE
Concatenation limit reached. Enabling `allOptional` maybe?

### ISSUE THREAD

**Issue by aseure** [algolia/hn-search#81]
A user informed us through support that the following search query doesn't get any result:
`This software startup can tell your boss if you’re looking for a job`

That's because of the backquote used instead of the single quote in the middle of `you're`. Maybe this can be fixed by setting `removeWordsIfNoResults` to `allOptional` (instead of `none`).

**Comment by redox** [comment]
> That's because of the backquote used instead of the single quote in the middle of you're. Maybe this can be fixed by setting removeWordsIfNoResults to allOptional (instead of none).

We tried already the `allOptional` but it's very confusing for such kind of story search use-case.

That being said, maybe this quote (it's not a backquote but a [RIGHT SINGLE QUOTATION MARK](https://www.cl.cam.ac.uk/~mgk25/ucs/quotes.html) - preferred character to use for apostrophe) should probably be handled by the API as well.

**Comment by Haroenv** [comment]
This has since been handled by the API, since `This software startup can tell your boss if you’re looking for a job` gives a single results (same as `you're`)
