### ISSUE TITLE
Quoted "exact" search terms not consistent when searching by date

### ISSUE THREAD

**Issue by Andrew-Hanlon** [algolia/hn-search#82]
If you change the search to be 'by date' rather than popularity, then quoted "exact" search terms with non alpha numeric characters are no longer respected in the result set.

Example: "C#" or ".net".

**Comment by redox** [comment]
Hey @Andrew-Hanlon,

good catch, the issue was actually not related to the quoted syntax but to the underlying indexing of punctuation characters. The indices used for the sorts weren't configured to use the `separatorsToIndex '+#$'`
