### ISSUE TITLE
Incremental search finds and then pressing enter loses?

### ISSUE THREAD

**Issue by Ealdwulf** [algolia/hn-search#84]
I'm seeing a strange issue where if I try incrementally into the top bar, I get results, but then I press enter and they go away, and it says there are no matches.

At the moment on this page: https://hn.algolia.com/?query=getflow&sort=byPopularity&prefix&page=0&dateRange=pastMonth&type=story
If I type 'getflow' then I get 4 results, and then they disappear when I press enter.

**Comment by redox** [comment]
Hey @Ealdwulf,

this is indeed an odd behavior. What happens here is the following:
 - by default the Algolia search engine will use prefix search (allowing `getf` to match `getflow` for instance) -> this is useful for find-as-you-type experience
 - while pressing `<enter>`, we send a new query to the API with the prefix search feature disabled -> this means the query is done, nothing should be suffixed anymore
 - on the indexing side, we're considering `.` as a special character to handle abbreviations and there is a side-effect of that -> `getflow.com` is considered as an abbreviation and therefore we're indexing `getflowcom` as a single token and `getflow` is not anymore matching `getflowcom`.

I'll check with the team what we can do here; definitely something we want to disable on that `host` attribute.

**Comment by JonasBa** [comment]
@Ealdwulf this is now fix for the use cases that have a dot. But indeed, the search right now finds results and when you press enter, we disable prefix search. I'm closing this as the case is fixed, but let us know if the UX is not something you think is good and if you maybe have an idea on how we could better handle this, we'd love to hear it :)
