### ISSUE TITLE
Custom date picker 

### ISSUE THREAD

**Issue by wamatt** [algolia/hn-search#85]
As per twitter conversation. Here are some suggestions for improvements to the search UX. 
- [ ] Add a "search" button to the date input.  This allows the mouse to be used to initiate a search

![image](https://cloud.githubusercontent.com/assets/1271434/19739929/a327fd6a-9b71-11e6-8007-45fd312e6dbc.png)
- [x] Allow keyboard input
- [x] Allow for partial input. eg specifying a year or just a year and month, instead of requiring a fully specified date
- [ ] Allow for an combination of from: or to: dates to be filled. If to: is left blank then search from to present date. If from is left blank then search from beginning of archive to the to: date. If both left blank, search entire date range.

**Comment by vvo** [comment]
Hi @wamatt, thanks for all the suggestions. Are you willing to provide a PR to solve this? That would be awesome!

**Comment by wamatt** [comment]
@vvo my pleasure. In theory, I'd be happy to do a PR :)

Let me see if time permits -- as I'd first need to familiarize myself with the stack and tooling.

**Comment by JonasBa** [comment]
@wamatt A bit late, but we'll try tackle this in https://github.com/algolia/hn-search/pull/150 :)

**Comment by JonasBa** [comment]
@wamatt We have fixed #1 and #2 issues you pointed out. For #3, we would just not recommend using a date option for search because by default it will search in all results :) Closing this and deploying the new version soon!
