### ISSUE TITLE
Allow reverse sorting

### ISSUE THREAD

**Issue by wamatt** [algolia/hn-search#86]
Suggestion. It would be handy to be able to search in reverse order for date and relevance. Specifically reverse date is useful.

**Comment by redox** [comment]
> Suggestion. It would be handy to be able to search in reverse order for date and relevance. Specifically reverse date is useful.

Reverse date could indeed by useful, but I'm not sure `reverse relevance` makes sense.

**Comment by wamatt** [comment]
I agree. The use case for `reverse relevance` would, at least at first glance, seem limited.

That said, making it behave differently to date search, breaks a small consistency principle.

Think 'Finder' in OSX. Any field can be added to the  view reversed, simply by clicking on it. I believe Explorer in Windows is the same.  
![image](https://cloud.githubusercontent.com/assets/1271434/19921043/5969d9dc-a099-11e6-82d3-abbc7a0733f0.png)

Therefor the user seemingly has a common affordance out the gate.

That said, it also depends how Algolia codes the results view on the backend. If it's non-trivial to implement, then is probably not be worth preserving consistency.
