### ISSUE TITLE
Template code has supurious space in handlebars causing syntax to break

### ISSUE THREAD

**Issue by TheChuckster** [algolia/hn-search#87]
See result count in repro screenshot:

![hn search powered by algolia](https://cloud.githubusercontent.com/assets/143290/20918218/b7fe4de0-bb4a-11e6-8452-092f7dafb57c.png)

**Comment by TheChuckster** [comment]
Seems okay in master _home-header.html.haml though, hmmm

**Comment by Shipow** [comment]
Thanks for reporting, we will dig.

**Comment by redox** [comment]
Thank guys for spotting it. My bad on that one, it's the result of a commit I did 2 days ago to fix a potential XSS.
