### ISSUE TITLE
Night theme support

### ISSUE THREAD

**Issue by nikitavoloboev** [algolia/hn-search#88]
I love this search, however it would be quite amazing to have night theme support. Similar to [hckrnews.com](http://hckrnews.com)

![2017-01-14 at 23 29](https://cloud.githubusercontent.com/assets/6391776/21958570/5838fa96-dab1-11e6-920d-324076d30297.png)

**Comment by redox** [comment]
I would love to merge a PR introducing such a dark theme. Do you think you could contribute adding a new theme: https://github.com/algolia/hn-search/tree/master/app/assets/stylesheets/themes I'll be happy to handle the JavaScript part if needed.

**Comment by JonasBa** [comment]
@nikitavoloboev I guess it's been a while, but we will take some time during an Algolia off-sprint to tackle this.

**Comment by JonasBa** [comment]
@nikitavoloboev this was implemented and you can toggle it on if you go under settings - experimental layout and you'll have a theme switch in the sidebar ;) Thanks for waiting all this time 😅
