### ISSUE TITLE
Interpolation in html attributes not working correctly

### ISSUE THREAD

**Issue by poacher2k** [algolia/hn-search#90]
Hi!
It seems like html attributes that are using interpolated values aren't working correctly, as `{{` ends up being ` { {` in the final output. This happens with both author, date, logo-url, settings-url, thumbnail-url, etc. Pretty much every single place where some attribute is using interpolated values.

![algolia](https://cloud.githubusercontent.com/assets/2255960/22788371/f6378068-eedf-11e6-8658-34c1ad04808e.png)

**Comment by redox** [comment]
Arg, good catch 👍
