### ISSUE TITLE
Settings are not applied for one user

### ISSUE THREAD

**Issue by aseure** [algolia/hn-search#97]
A user reported in our support mailbox that his search settings (the ranking options) don't seem to be respected, as shown on the following screenshots:

![image001](https://user-images.githubusercontent.com/3115191/27072020-5962274c-501f-11e7-9561-3a81cdf67e53.png)
![image002](https://user-images.githubusercontent.com/3115191/27072019-5960a2d2-501f-11e7-9c54-cce8ae3de132.png)

I've tried it on my own and I cannot reproduce it. Is it due to a JS blocker or could it be something on our side?

**Comment by JonasBa** [comment]
@aseure I guess we can close this, as we'd need more info to reproduce.
